### ISSUE TITLE
java.lang.IllegalStateException: SinchClient not started

### ISSUE THREAD

**Issue by omidjoon** [sinch/app-app-calling-android#16]
i ran your code and this is the error when i try to call 
`01-02 15:03:38.367 28039-28039/imedica.lakartorget.se E/AndroidRuntime: FATAL EXCEPTION: main
    Process: imedica.lakartorget.se, PID: 28039
    java.lang.IllegalStateException: SinchClient not started
        at com.sinch.android.rtc.internal.client.calling.DefaultCallClient.throwUnlessStarted(Unknown Source)
        at com.sinch.android.rtc.internal.client.calling.DefaultCallClient.call(Unknown Source)
        at com.sinch.android.rtc.internal.client.calling.DefaultCallClient.callUser(Unknown Source)
        at com.sinch.android.rtc.internal.client.calling.DefaultCallClient.callUser(Unknown Source)
        at imedica.lakartorget.se.presenters.provider.ProviderAcceptRequestFragmentPresenter.onVoiceCallRequest(ProviderAcceptRequestFragmentPresenter.java:132)
        at imedica.lakartorget.se.views.fragments.provider.ProviderAcceptRequestFragment.onCallRequestListener(ProviderAcceptRequestFragment.java:195)
        at imedica.lakartorget.se.viewHolders.provider.ProviderRequestConsultationHolder.onViewClicked(ProviderRequestConsultationHolder.java:127)
        at imedica.lakartorget.se.viewHolders.provider.ProviderRequestConsultationHolder_ViewBinding$4.doClick(ProviderRequestConsultationHolder_ViewBinding.java:77)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:5697)
        at android.view.View$PerformClick.run(View.java:22526)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7225)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

what should i do ? i follow the documentation

**Comment by deva-gopalani** [comment]
did you find a solution for the above issue buddy? i am facing the same problem... @omidjoon

**Comment by saintjab** [comment]
Any solution found yet?
