### ISSUE TITLE
sinch android video calling not working on android version 10

### ISSUE THREAD

**Issue by DevsAppsGroup** [sinch/app-app-calling-android#30]
I am getting this error when I try on android 10 version but another android version working fine what can i do for solve this problem. anyone know this problem? 
Please Help me 

This Error :-  
2020-10-06 17:14:55.267 21706-21706/com.demo.kktrstingapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.demo.kktrstingapp, PID: 21706
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.demo.kktrstingapp-daw6vzO9WmSV_peGoxVttg==/base.apk"],nativeLibraryDirectories=[/data/app/com.demo.kktrstingapp-daw6vzO9WmSV_peGoxVttg==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libsinch-android-rtc.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.sinch.android.rtc.internal.client.DefaultSinchClient.<clinit>(DefaultSinchClient.java:76)
        at com.sinch.android.rtc.internal.client.InternalSinchClientFactory.createSinchClient(InternalSinchClientFactory.java:19)
        at com.sinch.android.rtc.DefaultSinchClientBuilder.build(DefaultSinchClientBuilder.java:95)
        at com.demo.kktrstingapp.SinchService.start(SinchService.java:64)
        at com.demo.kktrstingapp.SinchService.access$500(SinchService.java:24)
        at com.demo.kktrstingapp.SinchService$SinchServiceInterface.startClient(SinchService.java:106)
        at com.demo.kktrstingapp.MainActivity.loginClicked(MainActivity.java:82)
        at com.demo.kktrstingapp.MainActivity.access$000(MainActivity.java:17)
        at com.demo.kktrstingapp.MainActivity$1.onClick(MainActivity.java:38)
        at android.view.View.performClick(View.java:6608)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6864)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by DevsAppsGroup** [comment]
> I am getting this error when I try on android 10 version but another android version working fine what can i do for solve this problem. anyone know this problem?
> Please Help me
> 
> This Error :-
> 2020-10-06 17:14:55.267 21706-21706/com.demo.kktrstingapp E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.demo.kktrstingapp, PID: 21706
> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.demo.kktrstingapp-daw6vzO9WmSV_peGoxVttg==/base.apk"],nativeLibraryDirectories=[/data/app/com.demo.kktrstingapp-daw6vzO9WmSV_peGoxVttg==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libsinch-android-rtc.so"
> at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
> at java.lang.System.loadLibrary(System.java:1669)
> at com.sinch.android.rtc.internal.client.DefaultSinchClient.(DefaultSinchClient.java:76)
> at com.sinch.android.rtc.internal.client.InternalSinchClientFactory.createSinchClient(InternalSinchClientFactory.java:19)
> at com.sinch.android.rtc.DefaultSinchClientBuilder.build(DefaultSinchClientBuilder.java:95)
> at com.demo.kktrstingapp.SinchService.start(SinchService.java:64)
> at com.demo.kktrstingapp.SinchService.access$500(SinchService.java:24)
> at com.demo.kktrstingapp.SinchService$SinchServiceInterface.startClient(SinchService.java:106)
> at com.demo.kktrstingapp.MainActivity.loginClicked(MainActivity.java:82)
> at com.demo.kktrstingapp.MainActivity.access$000(MainActivity.java:17)
> at com.demo.kktrstingapp.MainActivity$1.onClick(MainActivity.java:38)
> at android.view.View.performClick(View.java:6608)
> at android.view.View.performClickInternal(View.java:6585)
> at android.view.View.access$3100(View.java:785)
> at android.view.View$PerformClick.run(View.java:25921)
> at android.os.Handler.handleCallback(Handler.java:873)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:201)
> at android.app.ActivityThread.main(ActivityThread.java:6864)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
