### ISSUE TITLE
SSL Exception

### ISSUE THREAD

**Issue by umairsajid0017** [sinch/app-app-calling-android#31]
I'm unable to connect with the sinch server in Java android app. 
Using this SDK: **sinch-android-rtc-3.17.4.aar**
`Error while executing http request: 
    javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x7b107fda88: I/O error during system call, Connection reset by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
        at com.sinch.httpclient.HttpRequestProcessor.run(Unknown Source:32)
        at com.sinch.httpclient.AsyncTaskRequest$TaskImpl.doInBackground(Unknown Source:63)
        at com.sinch.httpclient.AndroidAsyncTask.doInBackground(Unknown Source:7)
        at com.sinch.httpclient.AndroidAsyncTask.doInBackground(Unknown Source:2)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by christoffer-a-sinch** [comment]
Hi @umairsajid0017 , can you please provide details on what device model and Android OS version this failure is occurring on?

**Comment by umairsajid0017** [comment]
Thanks for reply.

I'm using Xiaomi Note 9S - Android 10 - Location: Pakistan

**Comment by umairsajid0017** [comment]
Even this link is not working in my windows PC or any phone browser in my country. 

[https://clientapi.sinch.com/V2/Instance](https://clientapi.sinch.com/V2/Instance )

**Comment by umairsajid0017** [comment]
![image](https://user-images.githubusercontent.com/34675906/100948891-ab134f00-352a-11eb-9bbe-eadd15f52a5a.png)

**Comment by umairsajid0017** [comment]
Few other people are facing this problem too

https://stackoverflow.com/questions/64728868/javax-net-ssl-sslhandshakeexception-sinch-voice-call

**Comment by ahmadbajwa12315** [comment]
@umairsajid0017 did u find the solution?

**Comment by umairsajid0017** [comment]
> @umairsajid0017 did u find the solution?

Not yet, I'm going to use agora now.

**Comment by umairsajid0017** [comment]
@ahmadbajwa12315  please mention your phone, country and android version details here.

**Comment by ahmadbajwa12315** [comment]
I'm using huawei mate 10 lite - Android 8 - Location: Pakistan

**Comment by ahmadbajwa12315** [comment]
> > @umairsajid0017 did u find the solution?
> 
> Not yet, I'm going to use agora now.

I think this sdk is not supported in Pakistan.

**Comment by umairsajid0017** [comment]
> > > @umairsajid0017 did u find the solution?
> > 
> > 
> > Not yet, I'm going to use agora now.
> 
> I think this sdk is not supported in Pakistan.

Yes may be now. Because I had been develop few apps using sinch few months ago.

**Comment by ahmadbajwa12315** [comment]
> > > > @umairsajid0017 did u find the solution?
> > > 
> > > 
> > > Not yet, I'm going to use agora now.
> > 
> > 
> > I think this sdk is not supported in Pakistan.
> 
> Yes may be now. Because I had been develop few apps using sinch few months ago.

did you find any other sdk for app to app library?

**Comment by umairsajid0017** [comment]
> > > > > @umairsajid0017 did u find the solution?
> > > > 
> > > > 
> > > > Not yet, I'm going to use agora now.
> > > 
> > > 
> > > I think this sdk is not supported in Pakistan.
> > 
> > 
> > Yes may be now. Because I had been develop few apps using sinch few months ago.
> 
> did you find any other sdk for app to app voice call?

Yes agora.io can be used.

**Comment by christoffer-a-sinch** [comment]
@umairsajid0017 and @ahmadbajwa12315 , to comply with relevant laws and regulations we have unfortunately been required to suspend the Sinch RTC SDK services in Pakistan until further notice. If you have further questions on this particular matter please contact email support@sinch.com. We apologize for the inconvenience.
